{"uuid": "b575c606-dd9d-4e5b-a115-e3777acbf48c", "befores": [{"name": "check_light_mode", "status": "failed", "statusDetails": {"message": "AssertionError: Error : Get UDP syncPilot timeout!\n", "trace": "  File \"C:\\Users\\Ricardo.Lu\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Ricardo.Lu\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 957, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Ricardo.Lu\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 787, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"D:\\workspace\\wiz-automation-test-bitbuckeet\\WizAutomationTest\\Test_Suites\\Steps\\control_lamp_steps.py\", line 830, in check_light_mode\n    udp_sync_res = target.udp.get_udp_sync_pilot(light_name, act_type)\n  File \"D:\\workspace\\wiz-automation-test-bitbuckeet\\WizAutomationTest\\Wrapper\\wrapper_udp.py\", line 384, in get_udp_sync_pilot\n    assert False, \"Error : Get UDP syncPilot timeout!\"\n"}, "start": 1608747923561, "stop": 1608747935920}], "start": 1608747923561, "stop": 1608747939122}