{"uuid": "e4458d78-e442-4112-ab3e-2d0f458d4b88", "befores": [{"name": "target", "status": "broken", "statusDetails": {"message": "serial.serialutil.SerialException: could not open port 'COM4': PermissionError(13, 'Access is denied.', None, 5)\n", "trace": "  File \"C:\\Users\\600008165\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\600008165\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\600008165\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 924, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\workspace\\wiz-automation-test\\WizAutomatedSystemTest\\Test_Suites\\Tests\\conftest.py\", line 55, in target\n    return WrapperManage(app, para)\n  File \"C:\\workspace\\wiz-automation-test\\WizAutomatedSystemTest\\Wrapper\\wrapper_manage.py\", line 30, in __init__\n    self.light_serial[key] = WrapperSerial(parameters).light_serial(key)\n  File \"C:\\workspace\\wiz-automation-test\\WizAutomatedSystemTest\\Wrapper\\wrapper_serial.py\", line 18, in light_serial\n    return SerialPort(serial_port, baud_rate, light_name)\n  File \"C:\\workspace\\wiz-automation-test\\WizAutomatedSystemTest\\Utils\\serial_comm.py\", line 41, in __init__\n    self.open()\n  File \"C:\\workspace\\wiz-automation-test\\WizAutomatedSystemTest\\Utils\\serial_comm.py\", line 44, in open\n    self.ser.open()  # open port\n  File \"C:\\Users\\600008165\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\serial\\serialwin32.py\", line 62, in open\n    raise SerialException(\"could not open port {!r}: {!r}\".format(self.portstr, ctypes.WinError()))\n"}, "start": 1602741591324, "stop": 1602741591329}], "start": 1602741591324, "stop": 1602741599422}