{"uuid": "72e6bf3c-3a3a-470c-b123-43a0fa07edef", "befores": [{"name": "check_light_mode", "status": "failed", "statusDetails": {"message": "AssertionError: check light_1 light mode UDP syncPilot fail! should be 16, but was 12\n", "trace": "  File \"C:\\Users\\Ricardo.Lu\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Ricardo.Lu\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 957, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Ricardo.Lu\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 787, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"D:\\workspace\\wiz-automation-test-bitbuckeet\\WizAutomationTest\\Test_Suites\\Steps\\control_lamp_steps.py\", line 853, in check_light_mode\n    \", but was \" + str(udp_sync_res[\"params\"][\"sceneId\"])\n"}, "start": 1608572729283, "stop": 1608572731427}], "start": 1608572729283, "stop": 1608572735145}